name: Create TNBase Application Release

on:
  push:
    tags:
      - "v*.*.*.*"
      
jobs:
  release:
    #if: github.event.base_ref=='refs/heads/master
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    env:
      Solution_Name: TNBase.sln
      Setup_Project: TNBase.Setup\TNBase.Setup.vdproj
      Configuration: Release

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Set release version
      run: echo ("RELEASE_VERSION=" + $env:GITHUB_REF.replace('refs/tags/v', '')) >> $env:GITHUB_ENV

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
     
    - name: Setup VS Dev Environment
      uses: seanmiddleditch/gha-setup-vsdevenv@v3

    - name: Execute unit tests
      run: dotnet test
      
    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration

    - name: Create installation package
      run: devenv $env:Solution_Name /build $env:Configuration  /Project $env:Setup_Project

    - name: Upload release artifacts
      uses: actions/upload-artifact@v2
      with:
        name: "TNBase_v${{ env.RELEASE_VERSION }}"
        path: TNBase.Setup\Release
