name: Create TNBase Application Release

on:
  push:
    tags:
      - "v*"
      
jobs:

  release:
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: TNBase.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Get the version 
      id: get_version 
      run: echo ::set-output name=VERSION::$GITHUB_REF
      env:
        GITHUB_REF: ${{ github.ref }}
      
    - name: Set env
      run: echo "$GITHUB.REPOSITORY"
      env:
        GITHUB_REF: ${{ github.ref }}
        
    - name: Test
      run: |
        echo $RELEASE_VERSION
        echo "${{ steps.get_version.outputs.VERSION }}"
